### ISSUE TITLE
Disney ride waiting time regression

### ISSUE THREAD

**Issue by jeanmatthieud** [cubehouse/themeparks#169]
**Park**
Which park/resort has this issue?
* DisneylandResortMagicKingdom
* DisneylandResortCaliforniaAdventure
* DisneylandParisMagicKingdom
* DisneylandParisWaltDisneyStudios
* ShanghaiDisneyResortMagicKingdom

**Context**
- themeparks version used: 4.7.19
- Operating System: N/A

**Describe the bug**
Since the release 4.7.19, some disney parks are not getting the ride waiting time.
In fact, getting the park data seems to be the real issue.

**Output**
```
Park DisneylandParisMagicKingdom
    Get Park Wait Times
THEMEPARKS 16200: Making request to https://authorization.go.com/token
THEMEPARKS 16200: Calling POST:https://authorization.go.com/token
THEMEPARKS 16200: Found 'application/json' header from in HTTP request, parsing JSON data
THEMEPARKS 16200: Successfully fetched body for URL https://authorization.go.com/token
THEMEPARKS 16200: DisneylandParisMagicKingdom: Fetched new WDW access_token 192cdf019db24e03aaaad635a5ebfe5f, expires in 900, caching for a maximum of 810
THEMEPARKS 16200: Making request to https://api.wdpro.disney.go.com/explorer-service/public/ancestor-activities-schedules/dlp;entityType=destination
THEMEPARKS 16200: Calling get:https://api.wdpro.disney.go.com/explorer-service/public/ancestor-activities-schedules/dlp;entityType=destination
THEMEPARKS 16200: Found 'application/json' header from in HTTP request, parsing JSON data
THEMEPARKS 16200: Successfully fetched body for URL https://api.wdpro.disney.go.com/explorer-service/public/ancestor-activities-schedules/dlp;entityType=destination
THEMEPARKS 16200: Making request to https://api.wdpro.disney.go.com/facility-service/theme-parks/P1;destination=dlp/wait-times
THEMEPARKS 16200: Calling get:https://api.wdpro.disney.go.com/facility-service/theme-parks/P1;destination=dlp/wait-times
THEMEPARKS 16200: Found 'application/json' header from in HTTP request, parsing JSON data
THEMEPARKS 16200: Successfully fetched body for URL https://api.wdpro.disney.go.com/facility-service/theme-parks/P1;destination=dlp/wait-times
THEMEPARKS 16200: Making request to https://api.wdpro.disney.go.com/explorer-service/public/destinations/dlp;entityType=destination/facilities?region=fr
THEMEPARKS 16200: Calling POST:https://api.wdpro.disney.go.com/explorer-service/public/destinations/dlp;entityType=destination/facilities?region=fr
THEMEPARKS 16200: Network request failed attempt 0/3 for URL https://api.wdpro.disney.go.com/explorer-service/public/destinations/dlp;entityType=destination/facilities?region=fr
THEMEPARKS 16200: 415: {
  "errors": [
    {
      "typeId": "UNEXPECTED_ERROR",
      "message": "HTTP 415 Unsupported Media Type",
      "stackTrace": [
        "javax.ws.rs.ClientErrorException: HTTP 415 Unsupported Media Type",
        "at org.apache.cxf.jaxrs.utils.JAXRSUtils.findTargetMethod(JAXRSUtils.java:540)",
        "at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.processRequest(JAXRSInInterceptor.java:181)",
        "at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.handleMessage(JAXRSInInterceptor.java:86)",
        "at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)",
        "at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)",
        "at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:240)",
        "at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:223)",
        "at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:197)",
        "at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:149)",
        "at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:167)",
        "at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:286)",
        "at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:206)",
        "at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)",
        "at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:262)",
        "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)",
        "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)",
        "at com.disney.wdpro.service.common.filters.CacheControlFilter.doFilter(CacheControlFilter.java:101)",
        "at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)",
        "at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)",
        "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)",
        "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)",
        "at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)",
        "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)",
        "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)",
        "at com.disney.wdpro.service.common.filters.StopwatchFilter.doFilter(StopwatchFilter.java:57)",
        "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)",
        "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)",
        "at com.disney.wdpro.service.common.filters.ConversationIdFilter.doFilter(ConversationIdFilter.java:154)",
        "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)",
        "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)",
        "at com.disney.wdpro.service.common.filters.HttpHeadersFilter.doFilter(HttpHeadersFilter.java:120)",
        "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)",
        "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)",
        "at org.springframework.web.filter.ShallowEtagHeaderFilter.doFilterInternal(ShallowEtagHeaderFilter.java:87)",
        "at com.disney.wdpro.service.common.filters.NonCachingEtagFilter.doFilterInternal(NonCachingEtagFilter.java:56)",
        "at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
        "at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)",
        "at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)",
        "at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)",
        "at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)",
        "at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)",
        "at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)",
        "at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)",
        "at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)",
        "at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)",
        "at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)",
        "at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)",
        "at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)",
        "at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)",
        "at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)",
        "at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)",
        "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)",
        "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)",
        "at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)",
        "at java.lang.Thread.run(Thread.java:745)"
      ]
    }
  ]
}
```

**Comment by jeanmatthieud** [comment]
Introduced by #160
