### ISSUE TITLE
Couchbase Sync returns 502 

### ISSUE THREAD

**Issue by senorihl** [cubehouse/themeparks#201]
**Park**
All disney parks

**Context**
- themeparks version used: 5.1.10 (41a216e7aa0cdac5d7a3e0d7a67e3272faef062f)
- Operating System: Ubuntu 18.04

**Describe the bug**
When getting changes from couchbase a 502 error is thrown

**Output**
```
$ NODE_DEBUG=themeparks PARKID=DisneylandParisMagicKingdom npm run testonline

> themeparks@5.1.10 testonline /home/senorihl/code/cubehouse/themeparks
> mocha --exit lib/testonline.js

THEMEPARKS 28498: DisneylandParisMagicKingdom: Set useragent to Mozilla/5.0 (Linux; U; Android 1.5; en-us; htc_bahamas Build/CRB17) AppleWebKit/528.5  (KHTML, like Gecko) Version/3.1.2 Mobile Safari/525.20.1
THEMEPARKS 28498: Setting up database ":memory:"


  Park DisneylandParisMagicKingdom
    Get Park Wait Times
THEMEPARKS 28498: Database version out-of-date. Got: 0, wants: 5
THEMEPARKS 28498: Updating database version to 1...
THEMEPARKS 28498: Updating database version to 2...
THEMEPARKS 28498: Updating database version to 3...
THEMEPARKS 28498: Updating database version to 4...
THEMEPARKS 28498: Updating database version to 5...
THEMEPARKS 28498: CouchbaseChannelDisney[facilitystatus_dlp]: Fetching full state from nothing
Error getting initial state: Error: Initial state status code: 502 ["<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n"]
Error: Initial state status code: 502 ["<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n"]
    at needle.then (/home/senorihl/code/cubehouse/themeparks/lib/disney/couchbaseChannel.js:436:33)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
THEMEPARKS 28498: Making request to https://authorization.go.com/token
THEMEPARKS 28498: Calling POST:https://authorization.go.com/token
THEMEPARKS 28498: Found 'application/json' header from in HTTP request, parsing JSON data
THEMEPARKS 28498: Successfully fetched body for URL https://authorization.go.com/token
THEMEPARKS 28498: DisneylandParisMagicKingdom: Fetched new WDW access_token 9e9a57493ed341569e5a6e05474eda5e, expires in 900, caching for a maximum of 810
THEMEPARKS 28498: Making request to https://api.wdpro.disney.go.com/explorer-service/public/ancestor-activities-schedules/dlp;entityType=destination
THEMEPARKS 28498: Calling GET:https://api.wdpro.disney.go.com/explorer-service/public/ancestor-activities-schedules/dlp;entityType=destination
THEMEPARKS 28498: Found 'application/json' header from in HTTP request, parsing JSON data
THEMEPARKS 28498: Successfully fetched body for URL https://api.wdpro.disney.go.com/explorer-service/public/ancestor-activities-schedules/dlp;entityType=destination
THEMEPARKS 28498: CouchbaseChannelDisney[facilities_dlp]: Fetching full state from nothing
THEMEPARKS 28498: FacilityChannel: Error getting initial state: Error: Initial state status code: 502 ["<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n"]
Error: Initial state status code: 502 ["<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n"]
    at needle.then (/home/senorihl/code/cubehouse/themeparks/lib/disney/couchbaseChannel.js:436:33)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
THEMEPARKS 28498: FacilityChannel: No new facility data to bulk write to DB, skipping write
THEMEPARKS 28498: FacilityChannel: No new calendar data to bulk write to DB, skipping write
THEMEPARKS 28498: Making request to https://api.wdpro.disney.go.com/explorer-service/public/destinations/dlp;entityType=destination/facilities?region=fr
THEMEPARKS 28498: Calling POST:https://api.wdpro.disney.go.com/explorer-service/public/destinations/dlp;entityType=destination/facilities?region=fr
THEMEPARKS 28498: Found 'application/json' header from in HTTP request, parsing JSON data
THEMEPARKS 28498: Successfully fetched body for URL https://api.wdpro.disney.go.com/explorer-service/public/destinations/dlp;entityType=destination/facilities?region=fr
      ✓ should not return an error fetching ride times (3136ms)
      1) should have some ride data
      ✓ should have an ID for every ride
      ✓ should have a wait time for every operating ride (or should be null)
      ✓ should have a name for every ride
      ✓ should have an active state for every ride
      ✓ should have a fastpass field for every ride
      ✓ should have a status field for every ride
      ✓ should have matching status and active fields
    Get Schedule
THEMEPARKS 28498: Making request to https://api.wdpro.disney.go.com/explorer-service/public/ancestor-activities-schedules/dlp;entityType=destination
THEMEPARKS 28498: Calling GET:https://api.wdpro.disney.go.com/explorer-service/public/ancestor-activities-schedules/dlp;entityType=destination
THEMEPARKS 28498: Found 'application/json' header from in HTTP request, parsing JSON data
THEMEPARKS 28498: Successfully fetched body for URL https://api.wdpro.disney.go.com/explorer-service/public/ancestor-activities-schedules/dlp;entityType=destination
      ✓ should not error when fetching schedule (550ms)
      ✓ should have schedule data
      ✓ should have a valid date for each schedule entry
      ✓ should have a valid opening time for each schedule entry
      ✓ should have a valid closing time for each schedule entry (98ms)


  13 passing (4s)
  1 failing
```

**Comment by senorihl** [comment]
It seems that the hostname change cause even this

**Comment by cubehouse** [comment]
Will look into this tonight, but will welcome pull requests if anyone knows what is up.

**Comment by PhilippeP62** [comment]
Here , I couldn't check what it did wrong , but wait times for DLP weren't
updated starting at 10am Paris time....
Without doing anything , it works normal again since 7.30pm ... so maybe a
problem on the Disney side ?

And by the way , I really miss the rides opening times ... , they are in
the app , so they must exist somewhere !

Philippe

Le jeu. 27 juin 2019 à 11:04, Jamie Holding <notifications@github.com> a
écrit :

**Comment by mooreandrew** [comment]
Looks like a problem Disney's end:

https://www.reddit.com/r/WaltDisneyWorld/comments/c65xmo/anyone_know_whats_going_on_with_the_mk_wait_times/

**Comment by cubehouse** [comment]
Everything seems to be working again now? I just rebooted my instance and everything seems to be a-OK.

Can people confirm if they were having issues if they're now resolved?

**Comment by jeanmatthieud** [comment]
I saw the same issue today on DLP. I did not worried because the DLP endpoint was still available, but with constant values.
Seems to work now as a lot of rides are now closed.

**Comment by senorihl** [comment]
I can confirm its works again. Thanks everyone. I close this issue :wink:
