### ISSUE TITLE
Universal Parks "UnhandledPromiseRejectionWarning"

### ISSUE THREAD

**Issue by thomasstoeckert** [cubehouse/themeparks#226]
**Park**
Universal Studios Hollywood, Universal Studios Florida, Islands of Adventure, Volcano Bay, Universal Studios Japan.

**Context**
- themeparks version used: 5.1.15
- Operating System: Windows 10

**Describe the bug**
Attempting to call "GetWaitTimes" on any of the above parks returns an error, with Node directly reporting the error  
```
(node:2484) UnhandledPromiseRejectionWarning: Error: 401: {
  "type": "Buffer",
  "data": []
}
    at HTTP.then (C:\Users\Thoma\Programming\NodeJS\LogRideWaitTimes\logride-wait-times\node_modules\themeparks\lib\universal\universalparkbase.js:109:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
```

**Comment by thomasstoeckert** [comment]
Working Now. Not Sure why, but it is.

**Comment by thomasstoeckert** [comment]
Nope. It didn't work. I was mistaken.

**Comment by thomasstoeckert** [comment]
And it's working now. The only park which seems to maintain this issue for me is Universal Studios Japan, but who knows.
