### ISSUE TITLE
Could not locate the bindings file

### ISSUE THREAD

**Issue by lightswitchr** [cubehouse/themeparks#62]
Hi,

I'm attempting to install themeparks on a Node application running in Docker.

npm install works, and doesn't error, however when I then run my application I get the following error:

```
/app/node_modules/themeparks/node_modules/osmosis/node_modules/libxmljs-dom/node_modules/libxmljs/node_modules/bindings/bindings.js:88
  err = new Error('Could not locate the bindings file. Tried:\n'
        ^
Error: Could not locate the bindings file. Tried:
 → /app/node_modules/themeparks/node_modules/osmosis/node_modules/libxmljs-dom/node_modules/libxmljs/build/xmljs.node
 → /app/node_modules/themeparks/node_modules/osmosis/node_modules/libxmljs-dom/node_modules/libxmljs/build/Debug/xmljs.node
 → /app/node_modules/themeparks/node_modules/osmosis/node_modules/libxmljs-dom/node_modules/libxmljs/build/Release/xmljs.node
 → /app/node_modules/themeparks/node_modules/osmosis/node_modules/libxmljs-dom/node_modules/libxmljs/out/Debug/xmljs.node
 → /app/node_modules/themeparks/node_modules/osmosis/node_modules/libxmljs-dom/node_modules/libxmljs/Debug/xmljs.node
 → /app/node_modules/themeparks/node_modules/osmosis/node_modules/libxmljs-dom/node_modules/libxmljs/out/Release/xmljs.node
 → /app/node_modules/themeparks/node_modules/osmosis/node_modules/libxmljs-dom/node_modules/libxmljs/Release/xmljs.node
 → /app/node_modules/themeparks/node_modules/osmosis/node_modules/libxmljs-dom/node_modules/libxmljs/build/default/xmljs.node
 → /app/node_modules/themeparks/node_modules/osmosis/node_modules/libxmljs-dom/node_modules/libxmljs/compiled/4.8.3/linux/x64/xmljs.node
    at bindings (/app/node_modules/themeparks/node_modules/osmosis/node_modules/libxmljs-dom/node_modules/libxmljs/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/app/node_modules/themeparks/node_modules/osmosis/node_modules/libxmljs-dom/node_modules/libxmljs/lib/bindings.js:1:37)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/app/node_modules/themeparks/node_modules/osmosis/node_modules/libxmljs-dom/node_modules/libxmljs/index.js:4:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/app/node_modules/themeparks/node_modules/osmosis/node_modules/libxmljs-dom/index.js:3:19)
```

How can I resolve this?

**Comment by cubehouse** [comment]
This looks like an issue with libxmljs.

Have you tried looking at the other issue regarding libxmljs on this project?

Can you share what docker configuration you're using? Is this based on the node images, or something else?

**Comment by lightswitchr** [comment]
Hi, thanks.

I was using `node:argon` in my Dockerfile, but after I switched it to `node:boron` it now works!

**Comment by cubehouse** [comment]
That's unusual, but that is a later version of node, so that is better!

We run unit tests against node versions back to v4, so not sure why that happened for you. Will investigate when I can, but I expect it is just libxmljs (dependency of osmosis) being hard to install.

Glad you resolved it.
